
version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8844:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    volumes:
      - ./.env:/usr/share/nginx/html/.env

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./.env:/app/.env
