
version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8844:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./.env:/usr/share/nginx/html/.env
    depends_on:
      - backend
    networks:
      - vm-captain-network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    networks:
      - vm-captain-network

networks:
  vm-captain-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
